config/routes.rb
Rails.application.routes.draw do
  resources :users_profiles
  resources :profiles
  devise_for :users
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_many :users_profiles
	has_many :users, :through => :users_profiles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :users_profiles
  has_many :profiles, :through => :users_profiles
end

app/models/users_profile.rb
class UsersProfile < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name)
    end
end

app/controllers/users_profiles_controller.rb
class UsersProfilesController < ApplicationController
  before_action :set_users_profile, only: [:show, :edit, :update, :destroy]

  # GET /users_profiles
  # GET /users_profiles.json
  def index
    @users_profiles = UsersProfile.all
  end

  # GET /users_profiles/1
  # GET /users_profiles/1.json
  def show
  end

  # GET /users_profiles/new
  def new
    @users_profile = UsersProfile.new
    @profiles = Profile.all
    @users = User.all
  end

  # GET /users_profiles/1/edit
  def edit
  end

  # POST /users_profiles
  # POST /users_profiles.json
  def create
    @users_profile = UsersProfile.new(users_profile_params)

    respond_to do |format|
      if @users_profile.save
        format.html { redirect_to @users_profile, notice: 'Users profile was successfully created.' }
        format.json { render :show, status: :created, location: @users_profile }
      else
        format.html { render :new }
        format.json { render json: @users_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_profiles/1
  # PATCH/PUT /users_profiles/1.json
  def update
    respond_to do |format|
      if @users_profile.update(users_profile_params)
        format.html { redirect_to @users_profile, notice: 'Users profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_profile }
      else
        format.html { render :edit }
        format.json { render json: @users_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_profiles/1
  # DELETE /users_profiles/1.json
  def destroy
    @users_profile.destroy
    respond_to do |format|
      format.html { redirect_to users_profiles_url, notice: 'Users profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_profile
      @users_profile = UsersProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_profile_params
      params.require(:users_profile).permit(:user_id, :profile_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_profiles_helper.rb
module UsersProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/users_profiles/_form.html.erb
<%= form_for(users_profile) do |f| %>
  <% if users_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users_profile.errors.count, "error") %> prohibited this users_profile from being saved:</h2>

      <ul>
      <% users_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :profile_id %>
    <%= f.text_field :profile_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_profiles/edit.html.erb
<h1>Editing Users Profile</h1>

<%= render 'form', users_profile: @users_profile %>

<%= link_to 'Show', @users_profile %> |
<%= link_to 'Back', users_profiles_path %>

app/views/users_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_profiles.each do |users_profile| %>
      <tr>
        <td><%= users_profile.user.email %></td>
        <td><%= users_profile.profile.name %></td>
        <td><%= link_to 'Show', users_profile %></td>
        <td><%= link_to 'Edit', edit_users_profile_path(users_profile) %></td>
        <td><%= link_to 'Destroy', users_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users Profile', new_users_profile_path %>

app/views/users_profiles/new.html.erb
<h1>Perfiles</h1>

<%=form_for(@users_profile) do |f|%>

<%= f.label "Usuario"%>
<select>
<%= options_for_select([["dan",1],["man",2]],2)%>
</select>
<%end%>


<% render 'form', users_profile: @users_profile %>

<%= link_to 'Back', users_profiles_path %>

app/views/users_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @users_profile.user %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @users_profile.profile %>
</p>

<%= link_to 'Edit', edit_users_profile_path(@users_profile) %> |
<%= link_to 'Back', users_profiles_path %>

app/views/welcome/index.html.erb
<h1>Bienvenido</h1>